apiVersion: v1
clusters:
  - cluster:
      certificate-authority: /home/santoshdts/.minikube/ca.crt
      extensions:
        - extension:
            last-update: Sat, 04 Jun 2022 19:13:53 IST
            provider: minikube.sigs.k8s.io
            version: v1.25.2
          name: cluster_info
      server: https://192.168.49.2:8443
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Sat, 04 Jun 2022 19:13:53 IST
            provider: minikube.sigs.k8s.io
            version: v1.25.2
          name: context_info
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: /home/santoshdts/.minikube/profiles/minikube/client.crt
      client-key: /home/santoshdts/.minikube/profiles/minikube/client.key
